import { Inter } from "@next/font/google";
import Head from "next/head";
import Post from "../components/Post";
import styles from "../styles/Home.module.css";
import { fetchEntries } from "../utils/contentfulPosts";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ posts }) {
  console.log("posts", posts);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="posts">
          {posts.map((p) => {
            return (
              <Post key={p.title} description={p.description} title={p.title} />
            );
          })}
        </div>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const res = await fetchEntries();
  console.log("Site is building", res);
  const posts = res.map((p) => {
    return p.fields;
  });

  return {
    props: {
      posts,
    },
  };
}
